version: 2
sphinx:
   configuration: doc/conf.py
build:
  os: ubuntu-22.04
  tools:
    python: "3.8"
    nodejs: "16"
  apt_packages:
    - gettext
python:
  install:
    - method: pip
      path: ./src/
    - requirements: doc/requirements.rtd.txt
