# Generated by Django 4.2.16 on 2024-12-02 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pretixbase', '0271_alter_customer_locale_alter_question_question_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemaddon',
            name='item_dependency',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='addon_item_dependencies', to='pretixbase.item'),
        ),
    ]
