# Generated by Django 4.2.16 on 2024-12-02 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pretixbase', '0272_itemaddon_item_dependency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemaddon',
            name='item_dependency',
        ),
    ]
