# Generated by Django 4.2.16 on 2024-12-02 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pretixbase', '0274_itemaddon_item_dependency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemaddon',
            name='item_dependency',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_dependency_to', to='pretixbase.item'),
        ),
    ]
