# Generated by Django 4.2.16 on 2024-12-02 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pretixbase', '0275_alter_itemaddon_item_dependency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemaddon',
            name='item_dependency',
            field=models.PositiveIntegerField(default=None, null=True),
        ),
    ]
