# Generated by Django 4.2.16 on 2024-12-02 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pretixbase', '0276_alter_itemaddon_item_dependency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemaddon',
            name='item_dependency',
        ),
        migrations.AddField(
            model_name='item',
            name='addon_item_dependency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='addon_item_dependencies', to='pretixbase.item'),
        ),
    ]
