# Generated by Django 4.2.16 on 2024-12-02 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pretixbase', '0277_remove_itemaddon_item_dependency_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='addon_item_dependency',
        ),
        migrations.AddField(
            model_name='item',
            name='addon_item_dependency_id',
            field=models.PositiveIntegerField(default=None, null=True),
        ),
    ]
