# Generated by Django 4.2.16 on 2024-12-04 15:24

# NOVA: extended to add unique secret for each token field

from django.db import migrations, models
import pretix.base.models.orders


def generate_unique_secrets(apps, schema_editor):
    # Get the model dynamically
    Order = apps.get_model('pretixbase', 'Order')
    for order in Order.objects.all():
        # Always override the secret_token with a new unique value
        order.secret_token = pretix.base.models.orders.generate_secret()
        order.save(update_fields=['secret_token'])


class Migration(migrations.Migration):

    dependencies = [
        ('pretixbase', '0279_order_pretalx_secret_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='pretalx_secret_token',
            new_name='secret_token',
        ),
        migrations.RunPython(generate_unique_secrets),
    ]
